language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  # - TOXENV=py32
install:
  # Install blas/lapack/atlas and gfortran for Numpy
  # See: http://docs.scipy.org/doc/numpy/user/install.html
  - sudo apt-get install libblas-dev liblapack-dev libatlas-dev gfortran

  - pip install --quiet --use-mirrors tox

  # travis-ci assumes that the test hangs if there is no output for
  # long time.  So, let's run installation with "-v".
  # For example, see: https://travis-ci.org/tkf/fillplots/jobs/6160402
  - tox --notest -v
script:
  - tox
